// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetSnapshot():Promise<main.Snapshot>;

export function RequestClose(arg1:number):Promise<string>;
